install:
  - SET PATH=C:\msys64\mingw64\bin;c:\gopath\bin;%PATH%
  - go get -u github.com/golang/lint/golint

build: off

clone_folder: c:\gopath\src\github.com\dcos\dcos-cli

environment:
  GOPATH: c:\gopath
  NO_DOCKER: 1
  GO111MODULE: off

stack: go 1.11

test_script:
  - mingw32-make windows
  - mingw32-make test
