install:
  - SET PATH=C:\msys64\mingw64\bin;c:\gopath\bin;%PATH%
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.27.0

build: off

clone_folder: c:\dcos-cli

environment:
  GOPATH: c:\gopath
  NO_DOCKER: 1
  GO111MODULE: off

stack: go 1.12

test_script:
  - SET GO111MODULE=on
  - mingw32-make windows
  - mingw32-make test
